spring:
  datasource:
    url: ENC(a0peoKpQH7OYf9ZtCj5AkqGEkj3ariH4j+Wj8CGoiEBJExphuDkswV660eC0FGE7)
    username: ENC(SPj9M7iTAJNKo7BHhyjRhQ==)
    password: ENC(ibgYb748fANQ8mDX0EvwyvzRI2X/kUUo)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
