spring:
  datasource:
    url: ENC(QPrviyEUHtIsrqCYg+if+wg/IqIz055B3P6qFQIA9pHToKQ15raJurIPRtgKd07y)
    username: ENC(+XUcXvIjYlocEzOhJdVDHQ==)
    password: ENC(z78qrh/3JrfNpuxv1a9PTQNRAylKxKta)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
