spring:
  data:
    redis:
      host: ENC(wiFdx5nyNINqQbzXRcdL36wB9mxWAO3H)
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(0KfLmG4krCuj78h3NzbJ5w7daYodZMdlra/gPnPUIUMH9olEWVcshVtjRJhWCeQGMoYE8yRSQLsc/vHMHrsRz4OHUU6Xjq9U8pYlvP6Um010JwRyn4NldQ==)
            client-secret: ENC(38gm9Lh2aAy0LSarrLubfKrKnu69uvZSC44kEgiF3teY18tRlVR/EtSiAUa/x2Eb)
            redirect-uri: ENC(ULweVkfXHiZlOIFgyb87gjZWOTiyiHH7u6CYvsF9aKPJynso/4U027ymmvV0ccC/)
            scope: ENC(j37IUVM+yav4Q2/56wpouHMBZ5ngKInV)
  datasource:
    url: ENC(a0peoKpQH7OYf9ZtCj5AkqGEkj3ariH4j+Wj8CGoiEBJExphuDkswV660eC0FGE7)
    username: ENC(SPj9M7iTAJNKo7BHhyjRhQ==)
    password: ENC(ibgYb748fANQ8mDX0EvwyvzRI2X/kUUo)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
