spring:
  data:
    redis:
      host: ENC(Yx6ePWYuJO6/VMXsEEbuQA==)
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(zdpQbVNYzmVhXxEXKZn1iv4hkQedMeDEb8oy42nl4bF4Opxoioly4L8rLMi88beTgTYaQwDR0kwNpjRIQlXs7tX56VwyWrcB5CugHLpS7QBZr1FN/8YOOA==)
            client-secret: ENC(LMDBlNxlvEzCvQ2LSzLknseAnCB1b6FKNoBc6++mnHQNm/9a8H2JK1xXg3HLasEk)
            redirect-uri: ENC(XgSaOobZq5ailrG1vg+UsURNtkjlCqbd2s3J6Z/mllbuJSejUAZDVw==)
            scope: ENC(RVN8cKd2olpKaFLf2iu50NDkN2jnqJGf)
  datasource:
    url: ENC(6JlR8GrL0AW/FPo2jppRhBHRBv8QLI34Vgc2C084BUU9nnFssRhQfg==)
    username: ENC(+XUcXvIjYlocEzOhJdVDHQ==)
    password: ENC(z78qrh/3JrfNpuxv1a9PTQNRAylKxKta)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
